"""Phase 4 — write generated kernels and Execution classes into the MNN
source tree, and patch FuseExecution.cpp so it dispatches to them.

What we emit, per fingerprint <fp>:
  source/backend/opencl/execution/cl/mnnforge_<fp>.cl
  source/backend/opencl/execution/cl/mnnforge_<fp>_mnn_cl.cpp        ← regenerated
  source/backend/opencl/execution/cl/opencl_source_map.hpp           ← regenerated
  source/backend/opencl/execution/image/MnnForge<Fp>Execution.hpp
  source/backend/opencl/execution/image/MnnForge<Fp>Execution.cpp

What we patch, once total:
  source/backend/opencl/execution/image/FuseExecution.cpp
    + #include lines for each MnnForge<Fp>Execution.hpp
    + dispatch lines inside FuseCreator::onCreate()

The patches are bracketed by `// MNNFORGE-BEGIN` / `// MNNFORGE-END` markers
so a re-run idempotently replaces the previous block instead of accumulating.
"""
from __future__ import annotations
import hashlib
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from typing import List, Tuple

from .kernel_synth import synthesize_kernel
from .log import Logger
from .onnx_fsm import Pattern


MARKER_BEGIN = "// MNNFORGE-BEGIN (auto-generated; do not edit by hand)"
MARKER_END = "// MNNFORGE-END"


@dataclass
class Emission:
    """One pattern's emitted artifacts."""
    fingerprint: str
    fp_camel: str                    # e.g. "A3f8c12b"  for class names
    kernel_name: str                 # mnnforge_<fp>
    n_inputs: int
    cl_source: str
    cl_path: str
    exec_hpp_path: str
    exec_cpp_path: str


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

EXEC_HPP_TPL = """\
//
//  MnnForge{fp_camel}Execution.hpp
//  MNN
//
//  Auto-generated by mnnforge — do not edit by hand.
//
#ifndef MnnForge{fp_camel}Execution_hpp
#define MnnForge{fp_camel}Execution_hpp

#include "backend/opencl/execution/image/CommonExecution.hpp"

namespace MNN {{
namespace OpenCL {{

class MnnForge{fp_camel}Execution : public CommonExecution {{
public:
    MnnForge{fp_camel}Execution(const std::vector<Tensor *> &inputs, Backend *backend, const Op *op);
    virtual ~MnnForge{fp_camel}Execution() = default;
    virtual ErrorCode onEncode(const std::vector<Tensor *> &inputs,
                               const std::vector<Tensor *> &outputs) override;

private:
    OpenCLBackend *mOpenCLBackend = nullptr;
    uint32_t mMaxWorkGroupSize = 0;
    std::vector<uint32_t> mGlobalWorkSize{{1, 1, 1}};
    std::vector<uint32_t> mLocalWorkSize{{1, 1, 1}};
}};

}}  // namespace OpenCL
}}  // namespace MNN

#endif
"""


EXEC_CPP_TPL = """\
//
//  MnnForge{fp_camel}Execution.cpp
//  MNN
//
//  Auto-generated by mnnforge — do not edit by hand.
//
#include "backend/opencl/execution/image/MnnForge{fp_camel}Execution.hpp"
#include "backend/opencl/core/OpenCLBackend.hpp"
#include "backend/opencl/core/OpenCLRunningUtils.hpp"
#include "core/Macro.h"

namespace MNN {{
namespace OpenCL {{

MnnForge{fp_camel}Execution::MnnForge{fp_camel}Execution(
        const std::vector<Tensor *> &inputs, Backend *backend, const Op *op)
    : CommonExecution(backend, op) {{
    mUnits.resize(1);
    mOpenCLBackend = static_cast<OpenCLBackend *>(backend);
    auto runtime = mOpenCLBackend->getOpenCLRuntime();
    std::set<std::string> buildOptions;
    // Kernel program is registered in opencl_source_map.hpp as "{kernel_name}".
    mUnits[0].kernel = runtime->buildKernel(
        "{kernel_name}", "{kernel_name}", buildOptions,
        mOpenCLBackend->getPrecision(), inputs[0], inputs[0]);
    OPENCL_CHECK_KERNEL_CTOR(mUnits[0].kernel);
    mMaxWorkGroupSize = static_cast<uint32_t>(
        runtime->getMaxWorkGroupSize(mUnits[0].kernel));
}}

ErrorCode MnnForge{fp_camel}Execution::onEncode(
        const std::vector<Tensor *> &inputs,
        const std::vector<Tensor *> &outputs) {{
    auto &unit = mUnits[0];
    Tensor *output = outputs[0];
    std::vector<int> outputShape = tensorShapeFormat(output);
    const int outputBatch    = outputShape.at(0);
    const int outputHeight   = outputShape.at(1);
    const int outputWidth    = outputShape.at(2);
    const int outputChannels = outputShape.at(3);
    const int channelBlocks  = UP_DIV(outputChannels, 4);

    mGlobalWorkSize = {{
        static_cast<uint32_t>(channelBlocks),
        static_cast<uint32_t>(outputWidth),
        static_cast<uint32_t>(outputHeight * outputBatch),
    }};

    cl_int ret = CL_SUCCESS;
    uint32_t idx = 0;
    for (auto in : inputs) {{
        ret |= unit.kernel->get().setArg(idx++, openCLImage(in));
    }}
    for (auto out : outputs) {{
        ret |= unit.kernel->get().setArg(idx++, openCLImage(out));
    }}
    ret |= unit.kernel->get().setArg(idx++, mGlobalWorkSize[0]);
    ret |= unit.kernel->get().setArg(idx++, mGlobalWorkSize[1]);
    ret |= unit.kernel->get().setArg(idx++, mGlobalWorkSize[2]);
    MNN_CHECK_CL_SUCCESS(ret, "setArg MnnForge{fp_camel}");

    mLocalWorkSize = localWS3DDefault(
        mGlobalWorkSize, mMaxWorkGroupSize,
        mOpenCLBackend->getOpenCLRuntime(),
        "{kernel_name}", unit.kernel,
        mOpenCLBackend->getCLTuneLevel(), "MnnForge").first;
    mOpenCLBackend->recordKernel3d(unit.kernel, mGlobalWorkSize, mLocalWorkSize);
    unit.globalWorkSize = {{mGlobalWorkSize[0], mGlobalWorkSize[1], mGlobalWorkSize[2]}};
    unit.localWorkSize  = {{mLocalWorkSize[0], mLocalWorkSize[1], mLocalWorkSize[2]}};
    return NO_ERROR;
}}

}}  // namespace OpenCL
}}  // namespace MNN
"""


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _cl_dir(mnn_root: str) -> str:
    return os.path.join(mnn_root, "source", "backend", "opencl",
                        "execution", "cl")


def _image_dir(mnn_root: str) -> str:
    return os.path.join(mnn_root, "source", "backend", "opencl",
                        "execution", "image")


def _fp_camel(fp: str) -> str:
    # Hex string starts with a digit ~50% of the time. Prefix with 'F' if so.
    if not fp:
        return fp
    if fp[0].isdigit():
        return "F" + fp
    return fp[0].upper() + fp[1:]


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------

def emit_pattern(mnn_root: str, p: Pattern, log: Logger) -> Emission:
    """Emit .cl + Execution {hpp,cpp} for one pattern."""
    fp = p.fingerprint
    fp_camel = _fp_camel(fp)
    kernel_name = f"mnnforge_{fp}"
    n_inputs = len(p.occurrences[0].boundary_inputs)
    cl_source = synthesize_kernel(kernel_name, p.op_kinds, n_inputs)

    cl_path = os.path.join(_cl_dir(mnn_root), f"{kernel_name}.cl")
    hpp_path = os.path.join(_image_dir(mnn_root),
                            f"MnnForge{fp_camel}Execution.hpp")
    cpp_path = os.path.join(_image_dir(mnn_root),
                            f"MnnForge{fp_camel}Execution.cpp")

    with open(cl_path, "w") as fh:
        fh.write(cl_source)
    with open(hpp_path, "w") as fh:
        fh.write(EXEC_HPP_TPL.format(fp_camel=fp_camel))
    with open(cpp_path, "w") as fh:
        fh.write(EXEC_CPP_TPL.format(fp_camel=fp_camel,
                                     kernel_name=kernel_name))

    log.vinfo(f"  emitted {os.path.relpath(cl_path, mnn_root)}")
    log.vinfo(f"  emitted {os.path.relpath(hpp_path, mnn_root)}")
    log.vinfo(f"  emitted {os.path.relpath(cpp_path, mnn_root)}")

    return Emission(
        fingerprint=fp, fp_camel=fp_camel, kernel_name=kernel_name,
        n_inputs=n_inputs, cl_source=cl_source,
        cl_path=cl_path, exec_hpp_path=hpp_path, exec_cpp_path=cpp_path,
    )


# ---------------------------------------------------------------------------
# Run opencl_codegen.py to refresh the kernel-string registry
# ---------------------------------------------------------------------------

def regenerate_opencl_source_map(mnn_root: str, log: Logger) -> None:
    cl_dir = _cl_dir(mnn_root)
    script = os.path.join(cl_dir, "opencl_codegen.py")
    if not os.path.isfile(script):
        log.warn(f"opencl_codegen.py not found at {script}; "
                 "kernel string registry will be stale until you run it manually")
        return
    log.info("running opencl_codegen.py to refresh opencl_source_map.hpp")
    res = subprocess.run(
        ["python3", os.path.basename(script), "."],
        cwd=cl_dir, capture_output=True, text=True,
    )
    if res.returncode != 0:
        log.err(res.stdout)
        log.err(res.stderr)
        raise SystemExit(f"opencl_codegen.py failed (rc={res.returncode})")


# ---------------------------------------------------------------------------
# FuseExecution.cpp dispatch patch
# ---------------------------------------------------------------------------

def _build_dispatch_block(emissions: List[Emission]) -> str:
    """Generate the include + dispatch snippet inserted into FuseExecution.cpp."""
    includes = "\n".join(
        f'#include "backend/opencl/execution/image/MnnForge{e.fp_camel}Execution.hpp"'
        for e in emissions
    )
    cases = "\n".join(
        f'    if (param->type()->str() == "MnnForge_{e.fingerprint}") '
        f'{{ return new MnnForge{e.fp_camel}Execution(inputs, backend, op); }}'
        for e in emissions
    )
    return (
        f"{MARKER_BEGIN}\n"
        f"{includes}\n"
        f"namespace MNN {{ namespace OpenCL {{\n"
        f"static Execution *_mnnforge_dispatch(\n"
        f"    const std::vector<Tensor *> &inputs,\n"
        f"    const MNN::Op *op, Backend *backend) {{\n"
        f"    auto param = op->main_as_Extra();\n"
        f"    if (!param || !param->type()) return nullptr;\n"
        f"{cases}\n"
        f"    return nullptr;\n"
        f"}}\n"
        f"}} }}\n"
        f"{MARKER_END}\n"
    )


def patch_fuse_execution(mnn_root: str, emissions: List[Emission],
                         log: Logger) -> None:
    """Insert/refresh the mnnforge dispatch in FuseExecution.cpp.

    Idempotent: a previous MNNFORGE-BEGIN/END block is replaced atomically.
    Adds one dispatcher invocation at the start of FuseCreator::onCreate.
    """
    fpath = os.path.join(_image_dir(mnn_root), "FuseExecution.cpp")
    if not os.path.isfile(fpath):
        raise SystemExit(f"FuseExecution.cpp missing: {fpath}")

    # Backup once on first patch.
    backup = fpath + ".mnnforge.bak"
    if not os.path.exists(backup):
        shutil.copy2(fpath, backup)
        log.vinfo(f"  backup created: {backup}")

    src = open(fpath).read()

    # Strip any previous MNNFORGE block.
    src = re.sub(
        re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END) + r"\n?",
        "", src, flags=re.DOTALL,
    )
    # Strip our previously injected dispatch call inside FuseCreator (if any).
    src = re.sub(
        r"\s*//\s*MNNFORGE-DISPATCH\b.*?//\s*MNNFORGE-DISPATCH-END\n?",
        "\n", src, flags=re.DOTALL,
    )

    block = _build_dispatch_block(emissions)
    # Insert the block just before the namespace MNN line.
    ns_match = re.search(r"^namespace MNN\b", src, flags=re.MULTILINE)
    if ns_match is None:
        raise SystemExit("could not locate `namespace MNN` in FuseExecution.cpp")
    insert_at = ns_match.start()
    src = src[:insert_at] + block + "\n" + src[insert_at:]

    # Insert the dispatcher invocation at the top of FuseCreator::onCreate body.
    onCreate_re = re.compile(
        r"(class FuseCreator\b[^{]*\{[^}]*?onCreate\([^{]*\{)",
        re.DOTALL,
    )
    m = onCreate_re.search(src)
    if m is None:
        log.warn(
            "couldn't find FuseCreator::onCreate body — dispatch block "
            "was inserted but won't be called. Inspect FuseExecution.cpp."
        )
    else:
        injection = (
            "\n        // MNNFORGE-DISPATCH\n"
            "        if (auto *e = MNN::OpenCL::_mnnforge_dispatch(inputs, op, backend)) "
            "return e;\n"
            "        // MNNFORGE-DISPATCH-END"
        )
        src = src[:m.end()] + injection + src[m.end():]

    with open(fpath, "w") as fh:
        fh.write(src)
    log.ok(f"patched {os.path.relpath(fpath, mnn_root)} "
           f"(dispatch for {len(emissions)} kernel(s))")


def emit_all(mnn_root: str, patterns: List[Pattern], top_n: int,
             log: Logger) -> List[Emission]:
    accepted = patterns[:top_n]
    if not accepted:
        log.info("no patterns to emit")
        return []
    emissions: List[Emission] = []
    for p in accepted:
        try:
            e = emit_pattern(mnn_root, p, log)
            emissions.append(e)
        except ValueError as e:
            log.warn(f"  pattern {p.fingerprint}: synthesis failed ({e}) — skipped")
    if not emissions:
        return []
    regenerate_opencl_source_map(mnn_root, log)
    patch_fuse_execution(mnn_root, emissions, log)
    log.ok(f"emitted {len(emissions)} kernel/Execution pair(s) into MNN tree")
    return emissions


# ---------------------------------------------------------------------------
# Rollback (so users can revert mnnforge's MNN-tree edits)
# ---------------------------------------------------------------------------

def rollback(mnn_root: str, log: Logger) -> int:
    """Restore FuseExecution.cpp from .bak and remove all generated files."""
    fpath = os.path.join(_image_dir(mnn_root), "FuseExecution.cpp")
    backup = fpath + ".mnnforge.bak"
    n_removed = 0
    if os.path.exists(backup):
        shutil.copy2(backup, fpath)
        os.remove(backup)
        log.ok(f"restored {os.path.relpath(fpath, mnn_root)}")
    # Remove generated files.
    for fn in os.listdir(_cl_dir(mnn_root)):
        if fn.startswith("mnnforge_") and (fn.endswith(".cl")
                                           or fn.endswith("_mnn_cl.cpp")):
            os.remove(os.path.join(_cl_dir(mnn_root), fn))
            n_removed += 1
    for fn in os.listdir(_image_dir(mnn_root)):
        if fn.startswith("MnnForge") and (fn.endswith(".hpp")
                                          or fn.endswith(".cpp")):
            os.remove(os.path.join(_image_dir(mnn_root), fn))
            n_removed += 1
    log.ok(f"removed {n_removed} generated file(s)")
    # Re-run codegen so opencl_source_map.hpp drops the stale entries.
    regenerate_opencl_source_map(mnn_root, log)
    return n_removed
