"""Phase 4 — write generated kernels and Execution classes into the MNN
source tree, and patch FuseExecution.cpp so it dispatches to them.

What we emit, per fingerprint <fp>:
  source/backend/opencl/execution/cl/mnnforge_<fp>.cl
  source/backend/opencl/execution/cl/mnnforge_<fp>_mnn_cl.cpp        ← regenerated
  source/backend/opencl/execution/cl/opencl_source_map.hpp           ← regenerated
  source/backend/opencl/execution/image/MnnForge<Fp>Execution.hpp
  source/backend/opencl/execution/image/MnnForge<Fp>Execution.cpp

What we emit ONCE for all fingerprints together:
  tools/converter/source/onnx/MnnForgeOnnx.cpp
    Registers an ONNX→MNN converter for each MnnForge_<fp> op_type.
    Sets extra->engine = "MNN" so writeFb.cpp accepts it WITHOUT --allowCustomOp.

What we patch, once total:
  source/backend/opencl/execution/image/FuseExecution.cpp
    + #include lines for each MnnForge<Fp>Execution.hpp
    + dispatch lines inside FuseCreator::onCreate()

The patches are bracketed by `// MNNFORGE-BEGIN` / `// MNNFORGE-END` markers
so a re-run idempotently replaces the previous block instead of accumulating.
"""
from __future__ import annotations
import hashlib
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from typing import List, Tuple

from .kernel_synth import synthesize_kernel
from .log import Logger
from .onnx_fsm import Pattern


MARKER_BEGIN = "// MNNFORGE-BEGIN (auto-generated; do not edit by hand)"
MARKER_END = "// MNNFORGE-END"


@dataclass
class Emission:
    """One pattern's emitted artifacts."""
    fingerprint: str
    fp_camel: str                    # e.g. "A3f8c12b"  for class names
    kernel_name: str                 # mnnforge_<fp>
    n_inputs: int
    cl_source: str
    cl_path: str
    exec_hpp_path: str
    exec_cpp_path: str


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

EXEC_HPP_TPL = """\
//
//  MnnForge{fp_camel}Execution.hpp
//  MNN
//
//  Auto-generated by mnnforge — do not edit by hand.
//
#ifndef MnnForge{fp_camel}Execution_hpp
#define MnnForge{fp_camel}Execution_hpp

#include "backend/opencl/execution/image/CommonExecution.hpp"

namespace MNN {{
namespace OpenCL {{

class MnnForge{fp_camel}Execution : public CommonExecution {{
public:
    MnnForge{fp_camel}Execution(const std::vector<Tensor *> &inputs, Backend *backend, const Op *op);
    virtual ~MnnForge{fp_camel}Execution() = default;
    virtual ErrorCode onEncode(const std::vector<Tensor *> &inputs,
                               const std::vector<Tensor *> &outputs) override;

private:
    OpenCLBackend *mOpenCLBackend = nullptr;
    uint32_t mMaxWorkGroupSize = 0;
    std::vector<uint32_t> mGlobalWorkSize{{1, 1, 1}};
    std::vector<uint32_t> mLocalWorkSize{{1, 1, 1}};
}};

}}  // namespace OpenCL
}}  // namespace MNN

#endif
"""


EXEC_CPP_TPL = """\
//
//  MnnForge{fp_camel}Execution.cpp
//  MNN
//
//  Auto-generated by mnnforge — do not edit by hand.
//
#include "backend/opencl/execution/image/MnnForge{fp_camel}Execution.hpp"
#include "backend/opencl/core/OpenCLBackend.hpp"
#include "backend/opencl/core/OpenCLRunningUtils.hpp"
#include "core/Macro.h"

namespace MNN {{
namespace OpenCL {{

MnnForge{fp_camel}Execution::MnnForge{fp_camel}Execution(
        const std::vector<Tensor *> &inputs, Backend *backend, const Op *op)
    : CommonExecution(backend, op) {{
    mUnits.resize(1);
    mOpenCLBackend = static_cast<OpenCLBackend *>(backend);
    auto runtime = mOpenCLBackend->getOpenCLRuntime();
    std::set<std::string> buildOptions;
    // Kernel program is registered in opencl_source_map.hpp as "{kernel_name}".
    mUnits[0].kernel = runtime->buildKernel(
        "{kernel_name}", "{kernel_name}", buildOptions,
        mOpenCLBackend->getPrecision(), inputs[0], inputs[0]);
    OPENCL_CHECK_KERNEL_CTOR(mUnits[0].kernel);
    mMaxWorkGroupSize = static_cast<uint32_t>(
        runtime->getMaxWorkGroupSize(mUnits[0].kernel));
}}

ErrorCode MnnForge{fp_camel}Execution::onEncode(
        const std::vector<Tensor *> &inputs,
        const std::vector<Tensor *> &outputs) {{
    auto &unit = mUnits[0];
    Tensor *output = outputs[0];
    std::vector<int> outputShape = tensorShapeFormat(output);
    const int outputBatch    = outputShape.at(0);
    const int outputHeight   = outputShape.at(1);
    const int outputWidth    = outputShape.at(2);
    const int outputChannels = outputShape.at(3);
    const int channelBlocks  = UP_DIV(outputChannels, 4);

    mGlobalWorkSize = {{
        static_cast<uint32_t>(channelBlocks),
        static_cast<uint32_t>(outputWidth),
        static_cast<uint32_t>(outputHeight * outputBatch),
    }};

    cl_int ret = CL_SUCCESS;
    uint32_t idx = 0;
    for (auto in : inputs) {{
        ret |= unit.kernel->get().setArg(idx++, openCLImage(in));
    }}
    for (auto out : outputs) {{
        ret |= unit.kernel->get().setArg(idx++, openCLImage(out));
    }}
    ret |= unit.kernel->get().setArg(idx++, mGlobalWorkSize[0]);
    ret |= unit.kernel->get().setArg(idx++, mGlobalWorkSize[1]);
    ret |= unit.kernel->get().setArg(idx++, mGlobalWorkSize[2]);
    MNN_CHECK_CL_SUCCESS(ret, "setArg MnnForge{fp_camel}");

    mLocalWorkSize = localWS3DDefault(
        mGlobalWorkSize, mMaxWorkGroupSize,
        mOpenCLBackend->getOpenCLRuntime(),
        "{kernel_name}", unit.kernel,
        mOpenCLBackend->getCLTuneLevel(), "MnnForge").first;
    mOpenCLBackend->recordKernel3d(unit.kernel, mGlobalWorkSize, mLocalWorkSize);
    unit.globalWorkSize = {{mGlobalWorkSize[0], mGlobalWorkSize[1], mGlobalWorkSize[2]}};
    unit.localWorkSize  = {{mLocalWorkSize[0], mLocalWorkSize[1], mLocalWorkSize[2]}};
    return NO_ERROR;
}}

}}  // namespace OpenCL
}}  // namespace MNN
"""


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _cl_dir(mnn_root: str) -> str:
    return os.path.join(mnn_root, "source", "backend", "opencl",
                        "execution", "cl")


def _image_dir(mnn_root: str) -> str:
    return os.path.join(mnn_root, "source", "backend", "opencl",
                        "execution", "image")


def _onnx_converter_dir(mnn_root: str) -> str:
    return os.path.join(mnn_root, "tools", "converter", "source", "onnx")


def _fp_camel(fp: str) -> str:
    # Hex string starts with a digit ~50% of the time. Prefix with 'F' if so.
    if not fp:
        return fp
    if fp[0].isdigit():
        return "F" + fp
    return fp[0].upper() + fp[1:]


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------

def emit_pattern(mnn_root: str, p: Pattern, log: Logger) -> Emission:
    """Emit .cl + Execution {hpp,cpp} for one pattern."""
    fp = p.fingerprint
    fp_camel = _fp_camel(fp)
    kernel_name = f"mnnforge_{fp}"
    n_inputs = len(p.occurrences[0].boundary_inputs)
    cl_source = synthesize_kernel(kernel_name, p.op_kinds, n_inputs)

    cl_path = os.path.join(_cl_dir(mnn_root), f"{kernel_name}.cl")
    hpp_path = os.path.join(_image_dir(mnn_root),
                            f"MnnForge{fp_camel}Execution.hpp")
    cpp_path = os.path.join(_image_dir(mnn_root),
                            f"MnnForge{fp_camel}Execution.cpp")

    with open(cl_path, "w") as fh:
        fh.write(cl_source)
    with open(hpp_path, "w") as fh:
        fh.write(EXEC_HPP_TPL.format(fp_camel=fp_camel))
    with open(cpp_path, "w") as fh:
        fh.write(EXEC_CPP_TPL.format(fp_camel=fp_camel,
                                     kernel_name=kernel_name))

    log.vinfo(f"  emitted {os.path.relpath(cl_path, mnn_root)}")
    log.vinfo(f"  emitted {os.path.relpath(hpp_path, mnn_root)}")
    log.vinfo(f"  emitted {os.path.relpath(cpp_path, mnn_root)}")

    return Emission(
        fingerprint=fp, fp_camel=fp_camel, kernel_name=kernel_name,
        n_inputs=n_inputs, cl_source=cl_source,
        cl_path=cl_path, exec_hpp_path=hpp_path, exec_cpp_path=cpp_path,
    )


# ---------------------------------------------------------------------------
# source/backend/cpu/MnnForgeCPU.cpp — universal CPU fallback
#
# Aligns with MNN's add-new-op SKILL step 3 ("CPU is the universal fallback").
# Without this:
#   * MNN's GeometryComputerUtils marks ops with all-const inputs as
#     Schedule::CONSTANT and tries to evaluate them on the backup CPU
#     backend, which has no OpType_Extra creator → "Don't support type
#     [Extra]" + "Const Folder Error" warnings.
#   * Models can't run at all on backends other than OpenCL.
#
# The CPU executor parses extra->attr["op_kinds"] (semicolon-separated
# "Type:sub_kind:chain_pos" tokens, see onnx_surgery.py) and walks the chain
# step-by-step in plain C++ on fp32 arrays. Slow but correct, and produces
# bit-exact same output as the OpenCL fast path on fp32 inputs.
#
# Registers a single creator for OpType_Extra that returns nullptr for
# non-MnnForge Extra ops, preserving the existing behaviour for everything
# else.
# ---------------------------------------------------------------------------

CPU_STUB_TPL = '''\
//
//  MnnForgeCPU.cpp
//  MNN
//
//  Auto-generated by mnnforge — do not edit by hand.
//
//  CPU fallback for OpType_Extra ops with type starting with "MnnForge_".
//  Walks the chain described in extra->attr["op_kinds"] and applies each
//  primitive on fp32 arrays in plain C++.
//
#include <math.h>
#include <string>
#include <vector>
#include <algorithm>
#include "core/Macro.h"
#include "core/TensorUtils.hpp"
#include "backend/cpu/CPUBackend.hpp"
#include "MNN_generated.h"

namespace MNN {

class MnnForgeCPUExecution : public Execution {
public:
    MnnForgeCPUExecution(Backend *backend, const Op *op,
                         const std::vector<std::pair<int, int>> &steps)
        : Execution(backend), mSteps(steps) {}
    virtual ~MnnForgeCPUExecution() = default;

    virtual ErrorCode onResize(const std::vector<Tensor *> &,
                               const std::vector<Tensor *> &) override {
        return NO_ERROR;
    }

    virtual ErrorCode onExecute(const std::vector<Tensor *> &inputs,
                                const std::vector<Tensor *> &outputs) override {
        if (inputs.empty() || outputs.empty()) return INVALID_VALUE;
        const int N = inputs[0]->elementSize();
        for (auto in : inputs) {
            if (in->elementSize() != N) return NOT_SUPPORT;
        }
        if (outputs[0]->elementSize() != N) return NOT_SUPPORT;
        if (inputs[0]->getType().bytes() != 4) return NOT_SUPPORT;

        std::vector<float> cur(N), tmp(N);
        size_t input_cursor = 0;
        auto readF = [](const Tensor *t, std::vector<float> &dst) {
            const float *src = t->host<float>();
            std::copy(src, src + dst.size(), dst.begin());
        };
        if (mSteps.empty()) return NOT_SUPPORT;

        for (size_t i = 0; i < mSteps.size(); ++i) {
            int kind = mSteps[i].first;
            int sub  = mSteps[i].second;
            if (i == 0) {
                if (input_cursor >= inputs.size()) return NOT_SUPPORT;
                readF(inputs[input_cursor++], cur);
            }
            if (kind == 0) {
                if (input_cursor >= inputs.size()) return NOT_SUPPORT;
                readF(inputs[input_cursor++], tmp);
                apply_binary(sub, cur, tmp);
            } else if (kind == 1) {
                apply_unary(sub, cur);
            } else if (kind == 2) {
                apply_relu(cur);
            }
        }

        float *dst = outputs[0]->host<float>();
        std::copy(cur.begin(), cur.end(), dst);
        return NO_ERROR;
    }

private:
    void apply_binary(int sub, std::vector<float> &a, const std::vector<float> &b) {
        const size_t N = a.size();
        for (size_t i = 0; i < N; ++i) {
            switch (sub) {
                case 0: a[i] = a[i] + b[i]; break;
                case 1: a[i] = a[i] - b[i]; break;
                case 2: a[i] = a[i] * b[i]; break;
                case 3: a[i] = a[i] / b[i]; break;
                default: break;
            }
        }
    }
    void apply_unary(int sub, std::vector<float> &a) {
        const size_t N = a.size();
        for (size_t i = 0; i < N; ++i) {
            float x = a[i];
            switch (sub) {
                case 0:  a[i] = std::fabs(x); break;
                case 1:  a[i] = -x; break;
                case 5:  a[i] = std::sqrt(x); break;
                case 6:  a[i] = 1.0f / std::sqrt(x); break;
                case 7:  a[i] = std::exp(x); break;
                case 8:  a[i] = std::log(x); break;
                case 15: a[i] = 1.0f / x; break;
                case 18: a[i] = std::tanh(x); break;
                case 23: a[i] = 1.0f / (1.0f + std::exp(-x)); break;
                case 31: a[i] = 0.5f * x * (1.0f + std::tanh(
                            0.79788456f * (x + 0.044715f * x * x * x))); break;
                default: break;
            }
        }
    }
    void apply_relu(std::vector<float> &a) {
        for (auto &v : a) v = v > 0 ? v : 0;
    }

    std::vector<std::pair<int, int>> mSteps;
};

static std::vector<std::pair<int, int>> _parse_op_kinds(const std::string &s) {
    std::vector<std::pair<int, int>> out;
    size_t pos = 0;
    while (pos < s.size()) {
        size_t end = s.find(';', pos);
        std::string tok = s.substr(pos, end == std::string::npos
                                       ? std::string::npos : end - pos);
        size_t c1 = tok.find(':');
        size_t c2 = tok.find(':', c1 == std::string::npos ? 0 : c1 + 1);
        if (c1 == std::string::npos || c2 == std::string::npos) break;
        std::string typeName = tok.substr(0, c1);
        int sub = std::atoi(tok.substr(c1 + 1, c2 - c1 - 1).c_str());
        int kind = -1;
        if      (typeName == "BinaryOp") kind = 0;
        else if (typeName == "UnaryOp")  kind = 1;
        else if (typeName == "ReLU")     kind = 2;
        if (kind >= 0) out.emplace_back(kind, sub);
        if (end == std::string::npos) break;
        pos = end + 1;
    }
    return out;
}

class MnnForgeCPUCreator : public CPUBackend::Creator {
public:
    virtual Execution *onCreate(const std::vector<Tensor *> &,
                                const std::vector<Tensor *> &,
                                const MNN::Op *op,
                                Backend *backend) const override {
        if (op->type() != OpType_Extra) return nullptr;
        auto extra = op->main_as_Extra();
        if (!extra || !extra->type()) return nullptr;
        std::string type_str = extra->type()->str();
        if (type_str.rfind("MnnForge_", 0) != 0) return nullptr;
        std::string kinds;
        if (extra->attr() != nullptr) {
            for (int i = 0; i < (int)extra->attr()->size(); ++i) {
                auto a = extra->attr()->Get(i);
                if (a && a->key() && a->key()->str() == "op_kinds" && a->s()) {
                    kinds = a->s()->str();
                    break;
                }
            }
        }
        if (kinds.empty()) return nullptr;
        auto steps = _parse_op_kinds(kinds);
        if (steps.empty()) return nullptr;
        return new MnnForgeCPUExecution(backend, op, steps);
    }
};

REGISTER_CPU_OP_CREATOR(MnnForgeCPUCreator, OpType_Extra);

}  // namespace MNN
'''


def _cpu_dir(mnn_root: str) -> str:
    return os.path.join(mnn_root, "source", "backend", "cpu")


def emit_cpu_stub(mnn_root: str, log: Logger) -> str:
    """Emit source/backend/cpu/MnnForgeCPU.cpp."""
    out_dir = _cpu_dir(mnn_root)
    if not os.path.isdir(out_dir):
        log.warn(f"CPU dir missing: {out_dir} — skipping CPU stub emit")
        return ""
    fpath = os.path.join(out_dir, "MnnForgeCPU.cpp")
    with open(fpath, "w") as fh:
        fh.write(CPU_STUB_TPL)
    log.ok(f"wrote {os.path.relpath(fpath, mnn_root)}")
    return fpath


# ---------------------------------------------------------------------------
# tools/converter/source/onnx/MnnForgeOnnx.cpp
#
# Registers a single converter class that handles every MnnForge_<fp> op type
# emitted by Phase 5 of mnnforge. The converter sets:
#     dstOp->type             = OpType_Extra
#     dstOp->main.value->type = onnxNode->op_type()    (e.g. "MnnForge_a3b8c12d")
#     dstOp->main.value->engine = "MNN"
# The "MNN" engine string is what writeFb.cpp checks before deciding whether
# the op is recognized — see source/common/writeFb.cpp:200. Without this, a
# user would have to pass `--allowCustomOp` to MNNConvert.
# ---------------------------------------------------------------------------

ONNX_CONVERTER_TPL = """\
//
//  MnnForgeOnnx.cpp
//  MNNConverter
//
//  Auto-generated by mnnforge — do not edit by hand.
//
//  Registers an ONNX→MNN converter for every MnnForge_<fp> op type emitted
//  by mnnforge. We set extra->engine = "MNN" so writeFb.cpp does not reject
//  the op (see source/common/writeFb.cpp).
//
#include "onnxOpConverter.hpp"

DECLARE_OP_CONVERTER(MnnForgeOnnx);

MNN::OpType MnnForgeOnnx::opType() {{
    return MNN::OpType_Extra;
}}
MNN::OpParameter MnnForgeOnnx::type() {{
    return MNN::OpParameter_Extra;
}}

void MnnForgeOnnx::run(MNN::OpT *dstOp, const onnx::NodeProto *onnxNode,
                       OnnxScope *scope) {{
    auto extra      = new MNN::ExtraT;
    dstOp->main.type  = MNN::OpParameter_Extra;
    dstOp->main.value = extra;
    extra->engine   = "MNN";   // accepted by writeFb.cpp
    extra->type     = onnxNode->op_type();   // e.g. "MnnForge_a3b8c12d"

    for (const auto &srcAttr : onnxNode->attribute()) {{
        std::unique_ptr<MNN::AttributeT> a(new MNN::AttributeT);
        a->key = srcAttr.name();
        switch (srcAttr.type()) {{
            case onnx::AttributeProto_AttributeType_INT:
                a->i = static_cast<int32_t>(srcAttr.i());
                break;
            case onnx::AttributeProto_AttributeType_FLOAT:
                a->f = srcAttr.f();
                break;
            case onnx::AttributeProto_AttributeType_STRING:
                a->s = srcAttr.s();
                break;
            case onnx::AttributeProto_AttributeType_INTS:
                a->list.reset(new MNN::ListValueT);
                a->list->i.resize(srcAttr.ints_size());
                for (int i = 0; i < srcAttr.ints_size(); ++i) {{
                    a->list->i[i] = static_cast<int32_t>(srcAttr.ints(i));
                }}
                break;
            case onnx::AttributeProto_AttributeType_FLOATS:
                a->list.reset(new MNN::ListValueT);
                a->list->f.resize(srcAttr.floats_size());
                for (int i = 0; i < srcAttr.floats_size(); ++i) {{
                    a->list->f[i] = srcAttr.floats(i);
                }}
                break;
            case onnx::AttributeProto_AttributeType_STRINGS:
                a->list.reset(new MNN::ListValueT);
                a->list->s.resize(srcAttr.strings_size());
                for (int i = 0; i < srcAttr.strings_size(); ++i) {{
                    a->list->s[i] = srcAttr.strings(i);
                }}
                break;
            default:
                break;
        }}
        extra->attr.emplace_back(std::move(a));
    }}
}}

// One REGISTER_CONVERTER line per fingerprint mined by mnnforge.
{registrations}
"""


def emit_onnx_converter(mnn_root: str, emissions: List[Emission],
                        log: Logger) -> str:
    """Emit (or refresh) tools/converter/source/onnx/MnnForgeOnnx.cpp.

    Re-running with a different set of fingerprints overwrites the file
    cleanly — registrations are auto-generated from the emission list.
    """
    out_dir = _onnx_converter_dir(mnn_root)
    if not os.path.isdir(out_dir):
        log.warn(f"converter dir missing: {out_dir} — skipping converter emit")
        return ""
    # One REGISTER_CONVERTER line per fingerprint.
    regs = "\n".join(
        f"REGISTER_CONVERTER(MnnForgeOnnx, MnnForge_{e.fingerprint});"
        for e in emissions
    )
    src = ONNX_CONVERTER_TPL.format(registrations=regs)
    fpath = os.path.join(out_dir, "MnnForgeOnnx.cpp")
    with open(fpath, "w") as fh:
        fh.write(src)
    log.ok(f"wrote {os.path.relpath(fpath, mnn_root)} "
           f"({len(emissions)} registration(s))")
    return fpath


# ---------------------------------------------------------------------------
# Run opencl_codegen.py to refresh the kernel-string registry
# ---------------------------------------------------------------------------

def regenerate_opencl_source_map(mnn_root: str, log: Logger) -> None:
    cl_dir = _cl_dir(mnn_root)
    script = os.path.join(cl_dir, "opencl_codegen.py")
    if not os.path.isfile(script):
        log.warn(f"opencl_codegen.py not found at {script}; "
                 "kernel string registry will be stale until you run it manually")
        return
    log.info("running opencl_codegen.py to refresh opencl_source_map.hpp")
    res = subprocess.run(
        ["python3", os.path.basename(script), "."],
        cwd=cl_dir, capture_output=True, text=True,
    )
    if res.returncode != 0:
        log.err(res.stdout)
        log.err(res.stderr)
        raise SystemExit(f"opencl_codegen.py failed (rc={res.returncode})")


# ---------------------------------------------------------------------------
# FuseExecution.cpp dispatch patch
# ---------------------------------------------------------------------------

def _build_dispatch_block(emissions: List[Emission]) -> str:
    """Generate the include + dispatch snippet inserted into FuseExecution.cpp."""
    includes = "\n".join(
        f'#include "backend/opencl/execution/image/MnnForge{e.fp_camel}Execution.hpp"'
        for e in emissions
    )
    cases = "\n".join(
        f'    if (param->type()->str() == "MnnForge_{e.fingerprint}") '
        f'{{ return new MnnForge{e.fp_camel}Execution(inputs, backend, op); }}'
        for e in emissions
    )
    return (
        f"{MARKER_BEGIN}\n"
        f"{includes}\n"
        f"namespace MNN {{ namespace OpenCL {{\n"
        f"static Execution *_mnnforge_dispatch(\n"
        f"    const std::vector<Tensor *> &inputs,\n"
        f"    const MNN::Op *op, Backend *backend) {{\n"
        f"    auto param = op->main_as_Extra();\n"
        f"    if (!param || !param->type()) return nullptr;\n"
        f"{cases}\n"
        f"    return nullptr;\n"
        f"}}\n"
        f"}} }}\n"
        f"{MARKER_END}\n"
    )


def patch_fuse_execution(mnn_root: str, emissions: List[Emission],
                         log: Logger) -> None:
    """Insert/refresh the mnnforge dispatch in FuseExecution.cpp.

    Idempotent: a previous MNNFORGE-BEGIN/END block is replaced atomically.
    Adds one dispatcher invocation at the start of FuseCreator::onCreate.
    """
    fpath = os.path.join(_image_dir(mnn_root), "FuseExecution.cpp")
    if not os.path.isfile(fpath):
        raise SystemExit(f"FuseExecution.cpp missing: {fpath}")

    # Backup once on first patch.
    backup = fpath + ".mnnforge.bak"
    if not os.path.exists(backup):
        shutil.copy2(fpath, backup)
        log.vinfo(f"  backup created: {backup}")

    src = open(fpath).read()

    # Strip any previous MNNFORGE block.
    src = re.sub(
        re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END) + r"\n?",
        "", src, flags=re.DOTALL,
    )
    # Strip our previously injected dispatch call inside FuseCreator (if any).
    src = re.sub(
        r"\s*//\s*MNNFORGE-DISPATCH\b.*?//\s*MNNFORGE-DISPATCH-END\n?",
        "\n", src, flags=re.DOTALL,
    )

    block = _build_dispatch_block(emissions)
    # Insert the block just before the namespace MNN line.
    ns_match = re.search(r"^namespace MNN\b", src, flags=re.MULTILINE)
    if ns_match is None:
        raise SystemExit("could not locate `namespace MNN` in FuseExecution.cpp")
    insert_at = ns_match.start()
    src = src[:insert_at] + block + "\n" + src[insert_at:]

    # Insert the dispatcher invocation at the top of FuseCreator::onCreate body.
    onCreate_re = re.compile(
        r"(class FuseCreator\b[^{]*\{[^}]*?onCreate\([^{]*\{)",
        re.DOTALL,
    )
    m = onCreate_re.search(src)
    if m is None:
        log.warn(
            "couldn't find FuseCreator::onCreate body — dispatch block "
            "was inserted but won't be called. Inspect FuseExecution.cpp."
        )
    else:
        injection = (
            "\n        // MNNFORGE-DISPATCH\n"
            "        if (auto *e = MNN::OpenCL::_mnnforge_dispatch(inputs, op, backend)) "
            "return e;\n"
            "        // MNNFORGE-DISPATCH-END"
        )
        src = src[:m.end()] + injection + src[m.end():]

    with open(fpath, "w") as fh:
        fh.write(src)
    log.ok(f"patched {os.path.relpath(fpath, mnn_root)} "
           f"(dispatch for {len(emissions)} kernel(s))")


def emit_all(mnn_root: str, patterns: List[Pattern], top_n: int,
             log: Logger) -> List[Emission]:
    accepted = patterns[:top_n]
    if not accepted:
        log.info("no patterns to emit")
        return []
    emissions: List[Emission] = []
    for p in accepted:
        try:
            e = emit_pattern(mnn_root, p, log)
            emissions.append(e)
        except ValueError as e:
            log.warn(f"  pattern {p.fingerprint}: synthesis failed ({e}) — skipped")
    if not emissions:
        return []
    regenerate_opencl_source_map(mnn_root, log)
    patch_fuse_execution(mnn_root, emissions, log)
    emit_onnx_converter(mnn_root, emissions, log)
    emit_cpu_stub(mnn_root, log)
    log.ok(f"emitted {len(emissions)} kernel/Execution pair(s) into MNN tree")
    return emissions


# ---------------------------------------------------------------------------
# Rollback (so users can revert mnnforge's MNN-tree edits)
# ---------------------------------------------------------------------------

def rollback(mnn_root: str, log: Logger) -> int:
    """Restore FuseExecution.cpp from .bak and remove all generated files."""
    fpath = os.path.join(_image_dir(mnn_root), "FuseExecution.cpp")
    backup = fpath + ".mnnforge.bak"
    n_removed = 0
    if os.path.exists(backup):
        shutil.copy2(backup, fpath)
        os.remove(backup)
        log.ok(f"restored {os.path.relpath(fpath, mnn_root)}")
    # Remove generated files in source/backend/opencl/execution/cl
    for fn in os.listdir(_cl_dir(mnn_root)):
        if fn.startswith("mnnforge_") and (fn.endswith(".cl")
                                           or fn.endswith("_mnn_cl.cpp")):
            os.remove(os.path.join(_cl_dir(mnn_root), fn))
            n_removed += 1
    # Remove generated files in source/backend/opencl/execution/image
    for fn in os.listdir(_image_dir(mnn_root)):
        if fn.startswith("MnnForge") and (fn.endswith(".hpp")
                                          or fn.endswith(".cpp")):
            os.remove(os.path.join(_image_dir(mnn_root), fn))
            n_removed += 1
    # Remove generated converter in tools/converter/source/onnx
    onnx_dir = _onnx_converter_dir(mnn_root)
    if os.path.isdir(onnx_dir):
        cand = os.path.join(onnx_dir, "MnnForgeOnnx.cpp")
        if os.path.exists(cand):
            os.remove(cand)
            n_removed += 1
    # Remove CPU stub in source/backend/cpu
    cpu_dir = _cpu_dir(mnn_root)
    if os.path.isdir(cpu_dir):
        cand = os.path.join(cpu_dir, "MnnForgeCPU.cpp")
        if os.path.exists(cand):
            os.remove(cand)
            n_removed += 1
    log.ok(f"removed {n_removed} generated file(s)")
    # Re-run codegen so opencl_source_map.hpp drops the stale entries.
    regenerate_opencl_source_map(mnn_root, log)
    return n_removed
